[tox]
envlist =
    lint-py{312,313,314}
    dj{42,52}-py{312,313,314}

skip_missing_interpreters =
    true

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314
DJANGO=
    4.2: dj42
    5.2: dj52
[testenv]
deps =
    {[base]deps}
    dj42: Django>=4.2,<5.0
    dj52: Django>=5.2,<6.0
commands = python -m django test
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONPATH = {toxinidir}
    PYTHONWARNINGS = all

[pytest]
django_find_project = false
python_files = test_*.py

[base]
deps =
    -r requirements.txt
